### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by jgarte** [mookid/diffr#79]
Hi, The following tests fail for me when building:

```

---- test_cli::color_ok stdout ----
thread 'test_cli::color_ok' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test_cli.rs:83:17

---- test_cli::color_ok_multiple stdout ----
thread 'test_cli::color_ok_multiple' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test_cli.rs:83:17

---- test_cli::debug_flag stdout ----
thread 'test_cli::debug_flag' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test_cli.rs:83:17

---- test_cli::color_only_face_name stdout ----
thread 'test_cli::color_only_face_name' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test_cli.rs:83:17


failures:
    test_cli::color_invalid_attribute_name
    test_cli::color_invalid_color_not_done
    test_cli::color_invalid_color_value_ansi
    test_cli::color_invalid_color_value_name
    test_cli::color_invalid_color_value_rgb
    test_cli::color_invalid_face_name
    test_cli::color_ok
    test_cli::color_ok_multiple
    test_cli::color_only_face_name
    test_cli::debug_flag
```

Do you happen to know how I can make them pass?

**Comment by mookid** [comment]
hello @jgarte ,
yes, those tests assume that the binary exists; if I recall correctly you need to do `cargo build` (or `cargo build --release`, I can't check at the moment on my machine) before running it.
