### ISSUE TITLE
[Debian package] Unit tests failing

### ISSUE THREAD

**Issue by szubersk** [mookid/diffr#87]
Run inside schroot, Debian unstable.

```
warning: `diffr` (bin "diffr" test) generated 5 warnings
    Finished test [unoptimized + debuginfo] target(s) in 2.12s
     Running `/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/diffr-0adc4b1ff5ef71b1`

running 38 tests
test diffr_lib::tests_lib::compress_path_test ... ok
test diffr_lib::tests_lib::diff_sequences_test_1 ... ok
test diffr_lib::tests_lib::diff_sequences_test_2 ... ok
test diffr_lib::tests_lib::diff_sequences_test_3 ... ok
test diffr_lib::tests_lib::diff_sequences_test_4 ... ok
test diffr_lib::tests_lib::diff_sequences_test_7 ... ok
test diffr_lib::tests_lib::diff_sequences_test_6 ... ok
test diffr_lib::tests_lib::find_splitting_point_test ... ok
test diffr_lib::tests_lib::diff_sequences_test_5 ... ok
test diffr_lib::tests_lib::issue15_2 ... ok
test diffr_lib::tests_lib::diff_sequences_test_8 ... ok
test diffr_lib::tests_lib::range_equality_test ... ok
test diffr_lib::tests_lib::split_lines_test ... ok
test diffr_lib::tests_lib::issue27 ... ok
test diffr_lib::tests_lib::split_lines_append_test ... ok
test diffr_lib::tests_lib::test_get_lcs ... ok
test diffr_lib::tests_lib::issue15 ... ok
test diffr_lib::tests_lib::tokenize_test ... ok
test tests_app::first_after_escape_test ... ok
test tests_app::parse_line_number_test ... ok
test diffr_lib::tests_lib::test_optimize_partition ... ok
test tests_app::skip_all_escape_code_test ... ok
test tests_app::skip_token_test ... ok
test tests_app::test_width ... ok
test diffr_lib::tests_lib::to_usize_checked_negative_test - should panic ... ok
test tests_cli::color_invalid_attribute_name ... FAILED
test tests_cli::color_invalid_color_not_done ... FAILED
test tests_cli::color_invalid_color_value_ansi ... FAILED
test tests_cli::color_invalid_color_value_name ... FAILED
test tests_cli::color_invalid_color_value_rgb ... FAILED
test tests_cli::color_ok ... FAILED
test tests_cli::color_invalid_face_name ... FAILED
test tests_cli::color_only_face_name ... FAILED
test tests_cli::color_ok_multiple ... FAILED
test tests_cli::debug_flag ... FAILED
test tests_cli::line_numbers_style ... FAILED
test tests_cli::test_bad_argument ... FAILED
test diffr_lib::tests_lib::test_lcs_random ... ok

failures:

---- tests_cli::color_invalid_attribute_name stdout ----
thread 'tests_cli::color_invalid_attribute_name' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_invalid_attribute_name
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:140:5
   6: diffr::tests_cli::color_invalid_attribute_name::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:139:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_invalid_color_not_done stdout ----
thread 'tests_cli::color_invalid_color_not_done' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_invalid_color_not_done
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:180:5
   6: diffr::tests_cli::color_invalid_color_not_done::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:179:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_invalid_color_value_ansi stdout ----
thread 'tests_cli::color_invalid_color_value_ansi' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_invalid_color_value_ansi
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:160:5
   6: diffr::tests_cli::color_invalid_color_value_ansi::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:159:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_invalid_color_value_name stdout ----
thread 'tests_cli::color_invalid_color_value_name' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_invalid_color_value_name
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:150:5
   6: diffr::tests_cli::color_invalid_color_value_name::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:149:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_invalid_color_value_rgb stdout ----
thread 'tests_cli::color_invalid_color_value_rgb' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_invalid_color_value_rgb
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:170:5
   6: diffr::tests_cli::color_invalid_color_value_rgb::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:169:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_ok stdout ----
thread 'tests_cli::color_ok' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_ok
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:190:5
   6: diffr::tests_cli::color_ok::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:189:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_invalid_face_name stdout ----
thread 'tests_cli::color_invalid_face_name' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_invalid_face_name
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:120:5
   6: diffr::tests_cli::color_invalid_face_name::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:119:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_only_face_name stdout ----
thread 'tests_cli::color_only_face_name' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_only_face_name
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:130:5
   6: diffr::tests_cli::color_only_face_name::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:129:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::color_ok_multiple stdout ----
thread 'tests_cli::color_ok_multiple' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::color_ok_multiple
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:200:5
   6: diffr::tests_cli::color_ok_multiple::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:199:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::debug_flag stdout ----
thread 'tests_cli::debug_flag' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::debug_flag
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:110:5
   6: diffr::tests_cli::debug_flag::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:109:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::line_numbers_style stdout ----
thread 'tests_cli::line_numbers_style' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::line_numbers_style
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:218:5
   6: diffr::tests_cli::line_numbers_style::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:214:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- tests_cli::test_bad_argument stdout ----
thread 'tests_cli::test_bad_argument' panicked at 'spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests_cli.rs:83:29
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.63.0/library/core/src/result.rs:1055:23
   4: diffr::tests_cli::test_cli
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:83:17
   5: diffr::tests_cli::test_bad_argument
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:248:5
   6: diffr::tests_cli::test_bad_argument::{{closure}}
             at /usr/share/cargo/registry/diffr-0.1.5/src/tests_cli.rs:247:1
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests_cli::color_invalid_attribute_name
    tests_cli::color_invalid_color_not_done
    tests_cli::color_invalid_color_value_ansi
    tests_cli::color_invalid_color_value_name
    tests_cli::color_invalid_color_value_rgb
    tests_cli::color_invalid_face_name
    tests_cli::color_ok
    tests_cli::color_ok_multiple
    tests_cli::color_only_face_name
    tests_cli::debug_flag
    tests_cli::line_numbers_style
    tests_cli::test_bad_argument

test result: FAILED. 26 passed; 12 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s

error: test failed, to rerun pass `--bin diffr`
dh_auto_test: error: /usr/share/cargo/bin/cargo test --all returned exit code 101
make[1]: *** [debian/rules:6: override_dh_auto_test] Error 25
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:3: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

**Comment by mookid** [comment]
yes, this is because the tests need the binary in debug mode (you need `cargo build` before `cargo test`)

**Comment by szubersk** [comment]
Added `cargo build` before `cargo test`  and provisioned the binary location by `export DIFFR_TESTS_BINARY_PATH=./debian/diffr/usr/bin/diffr`.
